name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['1.6.20', '2.0.4', 'stable']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Nim
      uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run example
      run: nim c -r example.nim